# Algebra liniowa z zastosowaniami 1

## Ćwiczenia w sali komputerowej nr 3


Uzupełnij swoje dane i sprawdź, czy wyświetlają się poprawnie:

In [ ]:
IMIE_NAZWISKO = ""

print(IMIE_NAZWISKO)

Standardowo zaczniemy od wczytania biblioteki NumPy:

In [ ]:
import numpy as np

**UWAGA!** Podczas rozwiązywania zadań **nie wykorzystuj**  funkcji innych bibliotek, np. SciPy lub SymPy; nie korzystaj również z modułu `linalg` biblioteki NumPy. Podczas zajęć samodzielnie będziemy implementowali poszczególne klasyczne algorytmy.

## Metody bezpośrednie rozwiązywania układów równań liniowych

Jednym z podstawowych zagadnień, które rozwiązuje się metodami algebry liniowej, jest rozwiązywanie układów równań liniowych. Przypomnijmy, że w szkole średniej spotkaliśmy się z kilkoma metodami rozwiązywania układów równań liniowych, choć zwykle w odniesieniu tylko do dwóch równań z dwiema niewiadomymi. Prawdopodobnie omawiano przynajmniej trzy elementy z poniższej listy:

* metoda przeciwnych współczynników
* metoda przez podstawienie
* metoda wyznacznikowa
* metoda graficzna

W dalszym ciągu kursu algebry liniowej zobaczymy, w jaki sposób trzy pierwsze z powyższych sposobów można rozszerzyć do przypadku rozwiązywania układów wielu równań liniowych z wieloma niewiadomymi. 

Dzisiejsze laboratoria poświęcone są opisaniu *metody eliminacji Gaussa*, która przypomina metodę przeciwnych współczynników.

### 1. Zapis macierzowy układu równań

Przypomnijmy, że każdy układ równań liniowych można przedstawić w postaci macierzowej. Na przykład mając układ $m$ równań z $n$ niewiadomymi
$$
    \left\{ 
        \begin{matrix}
            a_{11} x_1 +  a_{12} x_2 + \dots + a_{1n}x_n = b_1\\
            a_{21} x_1 + a_{22} x_2  + \dots + a_{2n}x_n = b_2\\
            \vdots\\
            a_{m1} x_1 + a_{m2} x_2 + \dots + a_{mn}x_n = b_m\\
        \end{matrix}
     \right.
$$
możemy układ ten zapisać w postaci
$$
A x  = b,
$$
przy czym
$$
A = 
    \begin{bmatrix} 
        a_{11} &  a_{12} & \dots & a_{1n}\\
        a_{21} &  a_{22} & \dots & a_{2n}\\
        \dots  & \dots   & \ddots& \vdots\\
        a_{m1} &  a_{m2} & \dots & a_{mn}
    \end{bmatrix},\qquad 
x = 
    \begin{bmatrix}
        x_1\\
        x_2\\
        \vdots\\
        x_n
    \end{bmatrix},\qquad
    b = 
    \begin{bmatrix}
        b_1\\
        b_2\\
        \vdots\\
        b_m
    \end{bmatrix}.
$$
Macierz $A$ to tzw. *macierz układu*. 

##### **Zadanie 1** (rozgrzewka: 0,5 pkt.)

Czy rozwiązaniem układu równań

$$
\left\{
    \begin{matrix}
        x_1 + 5x_2 +3x_3 & = &14\\
         4x_2+2x_3+4x_4 & = &3\\
        3x_3+8x_4+6x_5 & = &16\\
        2x_1+4x_2 -2x_5 &= &0\\
        2x_1-x_3 & = &0
    \end{matrix}
\right.
$$

są liczby 

$$
x_1 = 0{,}75,\quad x_2 = 1{,}75,\quad x_3 = 1{,}5,\quad x_4  = -1{,}75,\quad x_5 = 4{,}25?
$$

Uzupełnij poniższą funkcję `is_syseq_solution()`, która będzie działać również dla innych układów równań.

In [ ]:
def is_syseq_solution(A, X, B_model):
    # UMIEŚĆ SWÓJ KOD TUTAJ

    return None

----

### 2. W jaki sposób, znając $A$ oraz $b$, obliczyć $x$?  

Na początek zajmować się będziemy przypadkiem, gdy macierz układu jest kwadratowa (odpowiada to sytuacji $n$ równań z $n$ niewiadomymi).

**Obserwacja**

Gdyby macierz układu miała specyficzną postać (np. była macierzą [górnotrójkątną](https://pl.wikipedia.org/wiki/Macierz_tr%C3%B3jk%C4%85tna)), to rozwiązanie układu byłoby proste. 
Macierz *górnotrójkątna* to macierz postaci

$$
\begin{bmatrix} 
        a_{11} &  a_{12} & a_{13} & \dots & a_{1 (n-1)} & a_{1n}\\
        0      &  a_{22} & a_{23} & \dots & a_{2 (n-1)} & a_{2n}\\
        0      & 0       & a_{33} & \dots & a_{3 (n-1)} & a_{3n}\\     
        \dots  & \dots   & \dots  & \dots & \ddots & \vdots \\
        0      &  0      & 0      & \dots & 0 & a_{nn}
    \end{bmatrix}
$$

##### **Zadanie 2** (2 pkt.)

Uzupełnij poniższą funkcję `backward_substitution()`, implementującą metodę [podstawienia wstecz](https://algowiki-project.org/en/Backward_substitution). Funkcja będzie rozwiązywała układ równań w przypadku, gdy macierz układu będzie górnotrójkątna, przy czym $A$ jest macierzą układu, a $b$ to wektor wyrazów wolnych. Gdy $A$ nie jest górnotrójkątna, zwróć `None`.

Np. dla układu równań
$$
\left\{ 
    \begin{matrix}
        x_1 -  2x_2 +3x_3 & = 9\\
        \phantom{x_1 -2} x_2+3x_3 & = 5\\
        \phantom{x_1 -  2x_2 +3}x_3 & = 2
    \end{matrix}
\right.
$$

spodziewanym rozwiązaniem jest

$$
x_1 =1,\ x_2 = -1,\ x_3 = 2 \; .
$$


Przykładowe przypadki testowe, które powinien przejść Twój kod:

```python
# przypadek testowy 1
A = np.array([
    [1, -2, 3],
    [0,  1, 3],
    [0,  0, 1]
])
B = np.array([9, 5, 2]) 
print(backward_substitution(A, B))
```

Oczekiwany wynik:

```plaintext
[ 1. -1.  2.]
```

```python
# przypadek testowy 2
A = np.array([
    [2,  3, -1,  4],
    [0,  1,  5, -2],
    [0,  0,  4,  1],
    [0,  0,  0,  3]
])
B = np.array([10, 3, 8, 6])
print(backward_substitution(A, B))
```

Oczekiwany wynik:

```plaintext
[ 2.5 -0.5  1.5  2. ]
```

```python
# przypadek testowy 3
A = np.array([
    [2,  3, -1],
    [1,  1,  5],
    [0,  0,  4]
])
B = np.array([4, 2, 3])
print(backward_substitution(A, B))
```

Oczekiwany wynik:

```plaintext
None
```

In [ ]:
def backward_substitution(A, B):
    # UMIEŚĆ SWÓJ KOD TUTAJ
    
    return None

----

A co z ogólną sytuacją? Czy da się powyższą metodą zastosować na pewnym etapie rozwiązań układu równań, nawet w przypadku, gdy macierz układu $A$ nie jest górnotrójkątna?

### 3. Metoda eliminacji Gaussa

Metoda eliminacji Gaussa (omówiona już na wykładzie oraz ćwiczeniach przy tablicy) pozwala sprowadzić dowolną macierz do postaci górnotrójkątnej (w przypadku macierzy nieosobliwej), a w ogólnym przypadku do postaci zredukowanej (z angielskiego [*reduced row echelon form*](https://en.wikipedia.org/wiki/Row_echelon_form)). Macierz jest w postaci *zredukowanej* (patrzy wykład), jeśli

* począwszy od pewnego wiersza wszystkie następne wiersze macierzy składają się z samych zer. Powyżej tego wiersza nie ma wierszy złożonych z samych zer,
* w każdym niezerowym wierszu pierwszy od lewej niezerowy wyraz jest równy $1$. Ten wyraz będziemy nazywać jedynką wiodącą wiersza,
* jeżeli dwa sąsiednie wiersze nie są złożone z samych zer, to wiodąca jedynka wyższego wiersza znajduje się na lewo od wiodącej jedynki niższego wiersza.

Okazuje się, że każdą macierz można przedstawić w postaci macierzy zredukowanej, a algorytm, który tego dokonuje nazywa się algorytmem *eliminacji Gaussa*. W czasie wykładu poznałaś/eś ten algorytm i dowiedziałaś/eś się, że sprowadzenie macierzy do postaci zredukowanej dokonuje się za pomocą tzw. operacji elementarnych, czyli 

* zamiany miejscami dwóch wierszy,
* pomnożenia wiersza przez niezerowy skalar (liczbę),
* dodanie do danego wiersza wielokrotności innego wiersza.

Okazuje się, że w praktyce obliczeniowej zwykle zachowuje się jak najwięcej własności wyjściowej macierzy. A dwie pierwsze z opisanych operacji elementarnych powoduja zmianę wyznacznika macierzy (o tym, czym jest [wyznacznik](https://pl.wikipedia.org/wiki/Wyznacznik), jeśli jeszcze o nim nie słyszałaś/eś, dowiesz się wkrótce). Z tego powodu w podstawowej wersji eliminacji Gaussa (ang. naive Gaussian elimination) dopuszcza się tylko jedną operacją elementarną 

* dodanie do danego wiersza wielokrotności innego wiersza

i macierz układu sprowadza się do macierzy górnotójkątnej.

W przypadku zerowego elementu głównego (czyli elementu diagonalnego za pomocą, którego zeruje się elementy poniżej głównej przekątnej w danej kolumnie) podstawowa wersja eliminacji Gaussa nie da rozwiązana, nawet jeżeli układ jest oznaczony.

**UWAGA!** W dalszej części zajęć zakładamy, że rozważamy macierze nieosobliwe i o niezerowym elemencie głównym.

**UWAGA!** Należy pamiętać, że w obliczeniach wykonywanych w arytmetyce **zmiennopozycyjnej nie przyrównuje się** dwóch liczbe zmiennopozycyjnych za pomocą operatora porównania, chyba że chce się porównać je bit po bicie.
Należy zatem zamiast sprawdzania warunku $a_{ii}=0$ sprawdzić, czy $|a_{ii}|<tol,$ gdzie $tol$ to zadana dokładność. 
Przyjmijmy $tol=10^{-10}.$

##### **Zadanie** 3 (2 pkt.)

Uzupełnij poniższą funkcję `matrix_ref()` sprowadzającą macierz $A$ do postaci górnotrójkątnej.

Np. dla macierzy 

$$
\begin{bmatrix}
    \phantom{-}1 & -2 & 3\\
    -1 & \phantom{-}1 & 0\\
    \phantom{-}2 & -5 & 5
\end{bmatrix}
$$

spodziewany wynik to

$$
\begin{bmatrix}
1 & -2 & \phantom{-}3\\
0 & -1 & \phantom{-}3\\
0 & \phantom{-}0 & -4
\end{bmatrix}
$$

Przykładowe przypadki testowe, które powinien przejść Twój kod:

```python
# przypadek testowy 1
A = np.array([
    [ 1, -2, 3],
    [-1,  1, 0],
    [ 2, -5, 5]
], dtype=np.float64)
print(matrix_ref(A))
```

Oczekiwany wynik:

```plaintext
[[ 1. -2.  3.]
 [ 0. -1.  3.]
 [ 0.  0. -4.]]
```

```python
# przypadek testowy 2
A = np.array([
    [2, 4],
    [1, 3]
], dtype=np.float64)
print(matrix_ref(A))
```

Oczekiwany wynik:

```plaintext
[[2. 4.]
 [0. 1.]]
```

In [ ]:
def matrix_ref(A):
    # UMIEŚĆ SWÓJ KOD TUTAJ
    
    return None

----

####  Rozwiązywanie układu równań liniowych poprzez sprowadzanie macierzy do postaci górnotrójkątnej i metodę podstawiania wstecz

Mając dany układ równań
$$
    \left\{ 
        \begin{matrix}
            a_{11} x_1 +  a_{12} x_2 + \dots + a_{1n}x_n = b_1\\
            a_{21} x_1 + a_{22} x_2  + \dots + a_{2n}x_n = b_2\\
            \dots\\
            a_{n1} x_1 + a_{n2} x_2 + \dots + a_{nn}x_n = b_n\\
        \end{matrix}
     \right.,
$$
tworzymy tzw. *macierz rozszerzoną* tego układu
$$
\begin{bmatrix} 
    a_{11} &  a_{12} & \dots & a_{1n} & b_1\\
    a_{21} &  a_{22} & \dots & a_{2n} & b_2\\
    \dots  & \dots   & \dots& \ddots & \vdots\\
    a_{n1} &  a_{n2} & \dots & a_{nn} & b_n
\end{bmatrix}.
$$
Wystarczy sprowadzić macierz rozszerzoną do postaci górnotrójkątnej i rozwiązać nowopowstały układ *metodą podstawiania wstecz*.

##### **Zadanie 4** (2 pkt.)

Uzupełnij poniższą funkcję `solution_Gauss()` rozwiązującą układ równań metodą eliminacji. W swoim rozwiązaniu użyj zaimplementowanych wcześniej funkcji `matrix_ref()` oraz `backward_substitution()`.

Np. dla poniższego układu
$$
\left\{
    \begin{matrix}
        x_1 - 2x_2 + 3 x_3 & = 9\\
        -x_1 + x_2 \phantom{+ 3 x_3} & = -4\\
        2x_1-5x_2 +5x_3  & = 17
    \end{matrix}
\right.
$$

spodziewana odpowiedź to 

$$
x_1 = 3{,}5,\ x_2 = -0{,}5,\ x_3 = 1{,}5 \; .
$$

Przykładowe przypadki testowe, które powinien przejść Twój kod:

```python
# przypadek testowy 1
A = np.array([
    [1, -2, 3],
    [-1, 1, 0],
    [2, -5, 5]
], dtype=np.float64)
B = np.array([[9, -4, 17]], dtype=np.float64)
print(solution_Gauss(A, B))
```

Oczekiwany wynik:

```plaintext
[ 3.5 -0.5  1.5]
```

```python
# przypadek testowy 2
A = np.array([
    [2, 1, -1, 3],
    [1, -2, 0, 1],
    [3, 1, 2, -1],
    [1, -1, -1, 2]
], dtype=np.float64)
B = np.array([[8, 1, 10, 1]], dtype=np.float64)
print(solution_Gauss(A, B))
```

Oczekiwany wynik:

```plaintext
[0.75 1.5  4.75 3.25]
```

In [ ]:
def solution_Gauss(A, B):
    # UMIEŚĆ SWÓJ KOD TUTAJ 

    return None

### 4. Rozkład LU macierzy

Rozkład macierzy (faktoryzacja) to przedstawienie macierzy jako iloczynu macierzy ,,prostszych" postaci. Określenie ,,prostsze" w różnych rozkładach jest różnie definiowane.

Rozkład LU to przedstawienie macierzy A jako iloczynu macierzy dolnotrójkątnej i górnotrójkątnej. Jednym z algorytmów uzyskania takiego rozkładu jest podstawowa metoda eliminacji Gaussa. 

Przeanalizujmy raz jeszcze przekształcenie macierzy do postaci górnotrójkątnej. Tym razem jednak zapisywac będziemy kolejne kroki algorytmu za pomocą mnożenia przez macierz. Rozważmy przykład 
$$
A = 
    \begin{bmatrix}
        1 & -3 & 0\\
        0 & \phantom{-}1 & 3\\
        2 & -10 & 2
    \end{bmatrix}.
$$
W celu uzyskania zera w trzecim wierszu pierwszej kolumny należy do trzeciego wiersza dodać wiersz pierwszy pomnożony przez $-2$. Możesz to zrobić, mnożąc macierz $A$ lewostronnie przez macierz
$$
L_1 =
\begin{bmatrix}
    \phantom{-}1 & 0 & 0\\
    \phantom{-}0 & 1 & 0\\
    -2 & 0 & 1
\end{bmatrix}.
$$
Sprawdź, co uzyskałaś/eś

In [ ]:
# WYKONAJ KOD

A = np.array([
    [1,-3, 0],
    [0, 1, 3],
    [2, -10, 2]
], dtype=np.float64)
L1 = np.array([
    [1,0,0],
    [0, 1, 0],
    [-2, 0,1]
], dtype=np.float64)

A1 = np.matmul(L1,A)

print(A1)

Dalej, aby wyzerować element w trzecim wierszu i drugiej kolumnie, wystarczy, że pomnożysz lewostronnie macierz $C$ przez macierz
$$
L_2 =
    \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        0 & 4 & 1
    \end{bmatrix}.
$$
Upewnij się, że rozumiesz skąd bierze się macierz $L_2$! Sprawdźmy

In [ ]:
# WYKONAJ KOD

L2 = np.array([
    [1,0,0],
    [0, 1, 0],
    [0, 4,1]
], dtype=np.float64)

A2 = np.matmul(L2,A1)

print(A2)

Otrzymaliśmy macierz górnotrójkątną $U$
$$
U = 
    \begin{bmatrix}
        1 & -3 & 0\\
        0 & \phantom{-}1 & 3\\
        0 & \phantom{-}0 & 14
    \end{bmatrix},
$$
która spełnia równość
$$
L_2L_1A = U.
$$
Jeśli pomnożymy obustronnie powyższą równość przez odwrotności macierzy $L_2$ oraz $L_1$ odpowiednio, to otrzymamy równość
$$
    A = L_1^{-1}L_2^{-1} U.
$$
Zobaczmy jeszcze czym jest iloczyn macierzy $L_1^{-1}L_2^{-1}$

In [ ]:
# WYKONAJ KOD

L = np.matmul(np.linalg.inv(L1),np.linalg.inv(L2))

print(L)

Okazuje się, że iloczyn macierzy dolnotrójkątnych jest macierzą dolnotrójkątną (to nie powinno Cię zaskoczyć, bo rozumiesz jak działa mnożenie macierzy), a do tego odwracanie macierzy typu $L_i$ jest bardzo proste: polega ono na zmianie znaku elementów znajdujących się pod główną przekątną (a to już wymaga zastanowienia, sprawdź proszę samodzielnie!).

Podsumowując, dokonując przekształcenia macierzy układu do postaci górntrójkątnej, przy okazji, dokonaliśmy [faktoryzacji](https://pl.wikipedia.org/wiki/Rozk%C5%82ad_na_czynniki) (czyli rozkładu na czynniki) wyjściowej macierzy za pomocą macierzy dolno i górnotrójkątnej
$$
\begin{bmatrix}
        1 & -3 & 0\\
        0 & \phantom{-}1 & 3\\
        2 & -10 & 2
    \end{bmatrix}
    =
    \begin{bmatrix}
    1 & \phantom{-}0 & 0\\
    0 & \phantom{-}1 & 0\\
    2 & -4 & 1
\end{bmatrix}
\begin{bmatrix}
        1 & -3 & 0\\
        0 & \phantom{-}1 & 3\\
        0 & \phantom{-}0 & 14
    \end{bmatrix}.
$$
To ułatwia rozwiązywanie układów równań liniowych, szczególnie w sytuacji, gdy do rozwiązania mamy układy, w których zmienia się wektor wyrazów wolnych, a macierz układu jest taka sama (nie trzeba stosowac metody eliminacji Gaussa za każdym razem). 

Przedstawienie macierzy układu w postaci iloczynu macierzy trójkątych pozwala również na rozwiązywanie układu równań w następujący sposób
$$
A x = LU x = b,
$$
to podstawiając $y= Ux$ (wektor kolumnowy zmiennych $y$) otrzymujemy układ równań 
$$
Ly=b,
$$
który jest łatwo rozwiązać (gdyż macierz $L$ jest dolnotrójkątna, czyli stosujemy [podstawianie w przód](https://algowiki-project.org/en/Forward_substitution), ang. forward substution). Następnie, znaną już metodą (patrz zadanie 1) możemy wyznaczyć $x$.

##### **Zadanie** 5 (2 pkt.)

Uzupełnij funkcję `solution_lu_given()`, która rozwiązuje układy równań korzystając z rozkładu macierzy układu na iloczyn macierzy dolno- i górnotrójkątnej. Przy rozwiązaniu tego zadania wykorzystaj napisaną wcześniej funkcję `backward_substitution()` oraz funkcję `forward_substitution()`, w której zaimplementujesz metodę podstawienia w przód.

Np. dla poniższego układu równań

$$
\left\{
    \begin{matrix}
        x_1-3x_2 & = -5\\
        x_2+3x_3 & = -1\\
        2x_1-10x_2+2x_3 & = -20 
    \end{matrix}.
\right.
$$

spodziewana odpowiedź to
$$
    x_1=-24.71428571,\quad x_2 = -6.57142857,\quad x_3 = 1.85714286.
$$

Przykładowe przypadki testowe, które powinien przejść Twój kod:

```python
# przypadek testowy 1
L = np.array([
    [ 1,  0,  0],
    [ 0,  1,  0],
    [ 2, -4,  1]
], dtype=np.float64)
B = np.array([-5, -1, 20], dtype=np.float64)
print(forward_substitution(L, B))
```

Oczekiwany wynik:

```plaintext
[-5. -1. 26.]
```

```python
# przypadek testowy 2
L = np.array([
    [ 1,  0,  0],
    [ 0,  1,  0],
    [ 2, -4,  1]
], dtype=np.float64)

U = np.array([
    [ 1, -3,  0],
    [ 0,  1,  3],
    [ 0,  0, 14]
], dtype=np.float64)

B = np.array([-5, -1, 20], dtype=np.float64)

print(solution_lu_given(L, U, B))
```

Oczekiwany wynik:

```plaintext
[-24.71428571  -6.57142857   1.85714286]
```

In [ ]:
def forward_substitution(L, B):
    # UMIEŚĆ SWÓJ KOD TUTAJ

    return None

def solution_lu_given(L, U, B):
    # UMIEŚĆ SWÓJ KOD TUTAJ
    
    return None


Do rozkładu macierzy na iloczyn macierzy trójkatnych jeszcze wrócisz (m.in wtedy, gdy poznasz [algorytm Doolittle'a](https://pl.wikipedia.org/wiki/Metoda_LU) rozkładu macierzy na iloczyn $LU$), ale już nie w czasie dzisiejszych zajęć.

### 5. Zastosowanie układów równań liniowych

Rozwiązywanie układów równań liniowych ma wiele zastosowań. Poniżej znajduje się opis jednego z nich. Wyobraź sobie, że masz $n+1$ punktów na płaszczyźnie i chciał(a)byś znaleźć funkcję, której wykres przechodzi przez dane punkty. 

W jakiej klasie funkcji szukać rozwiązania? 

Możliwie najprostszej, czyli na przykład w klasie wielomianów. 

**W jaki sposób, mając $n+1$ punktów na płaszczyźnie, znaleźć wielomian stopnia nie wyższego niż $n$ przechodzący przez te punkty?** Tego typu zagadnienie nazywa się [interpolacją wielomianową](https://pl.wikipedia.org/wiki/Interpolacja_wielomianowa). Istnieją wydajne metody znalezienia wielomianu interpolacyjnego (np. [metoda Newtona](https://pl.wikipedia.org/wiki/Posta%C4%87_Newtona_wielomianu)), natomiast poniżej opisane jest podejście oparte o rozwiązanie układu równań liniowych opisanych [macierzą Vandermonde'a](https://pl.wikipedia.org/wiki/Macierz_Vandermonde%E2%80%99a).

Załóżmy, że mamy $n+1$ punktów na płaszczyźnie
$$
(x_0,y_0),\ (x_1,y_1),\dots,\ (x_{n},y_{n}).
$$
Szukamy takiego wielomianu (współczynników $a_i$, $i=0,1,\dots,n$)
$$
W_n(x) = a_0 + a_1x+\dots+a_n x^n, 
$$
że
$$
W_n(x_i) = y_i,\quad i=0,1,\dots,n.
$$
Z powyższego równania otrzymujemy układ $n+1$ równań z $n+1$ niewiadomymi
$$
\left\{
    \begin{matrix}
        a_0 + a_1 x_0 + a_2 x_0^2 +\dots+a_nx_0^n = y_0\\
        a_0 + a_1 x_1 + a_2 x_1^2 +\dots+a_nx_1^n = y_1\\
        \vdots\\
        a_0 + a_1 x_n + a_2 x_n^2 +\dots+a_nx_n^n = y_n
    \end{matrix}
\right.
$$
Zwróć proszę uwagę, że niewiadomymi są współczynniki $a_i$ wielomianu $W_n$!

##### **Zadanie** 6 (1,5 pkt.)

Liczba ludności Polski w roku 1978 wynosiła 35,06 mln, w roku 2000 wynosiła 38,65 mln, a w 2021 roku – 38,10 mln (dane za [GUS](https://stat.gov.pl/)). Przyjmując, że sytuację demograficzną Polski opisuje wielomian stopnia drugiego, znajdź teoretyczną liczbę ludności Polski w 2010 roku (faktycznie - 38,53 mln) oraz przewidywaną liczbę w latach 2025 oraz 2030 (**UWAGA!** To już jest [ekstrapolacja](https://pl.wikipedia.org/wiki/Ekstrapolacja), ale na potrzeby zadania możemy spróbować określić jak zachowuje się wielomian interpolacyjny poza przedziałem interpolacji). Zbuduj i rozwiąż odpowiedni układ równań liniowych, uzupełniając funkcję `expected_number()` oraz definując macierze `A` i `B`.   



Przykładowe przypadki testowe, które powinien przejść Twój kod:

```python
expected_number(X, 2010)
expected_number(X, 2025)
expected_number(X, 2030)
```

Oczekiwany wynik:

```plaintext
Liczba ludności w 2010: 38.872536 mln
Liczba ludności w 2025: 37.554837 mln
Liczba ludności w 2030: 36.675204 mln
```

In [ ]:
def expected_number(X, Year):
    # UMIEŚĆ SWÓJ KOD TUTAJ
    no = None
    print(f'Liczba ludności w {Year}: {no:.6f} mln')

A = None # UMIEŚĆ SWÓJ KOD TUTAJ
B = None # UMIEŚĆ SWÓJ KOD TUTAJ
X = solution_Gauss(A, B)

Z problemem interpolacji wielomianowej spotkasz się jeszcze na zajęciach (choć nie na zajęciach z algebry liniowej), gdyż to ważne współcześnie zagadnienie, szczególnie w odniesieniu do interpolacji tzw. [funkcjami sklejanymi](https://pl.wikipedia.org/wiki/Funkcja_sklejana).  

### 6. Niedoskonałości podstawowej metody eliminacji Gaussa

Metoda eliminacji Gaussa, choć bardzo użyteczna, nie jest uniwersalna. Nie da rozwiązania równania, jeśli na przykład na jakimś etapie na głównej przekątnej pojawi się zero. Czasami może prowadzić do fałszywych wniosków, np. gdy element główny jest wiele rzędów wielkości mniejszy od pozostałych elementów macierzy, a działania wykonujemy w skończonej arytmetyce zmiennopozycyjnej.

Rozważmy macierz $A$ jak poniżej.

In [ ]:
# WYKONAJ KOD

A = np.array([
    [1e-20, 0, 1],
    [1, 1e+20, 1],
    [0, 1, -1]
])

X = np.array([[1,2,1]])

print(matrix_ref(A))

B = A @ X.transpose()
print(B)

Macierz B (jest postacią zredukowaną macierzy $A$) i ma w tej arytmetyce ostatni wiersz zerowy. Podstawowa metoda eliminacji Gaussa nie pozwala na znalezienie rozwiązania. Jednak jak widać powyżej $A$ jest macierzą układu mającego rozwiązanie. Jak znaleźć rozwiązanie takiego układu? To już opowieść na kolejne spotkanie... Do zobaczenia!